import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/common/Header";
import { NextAuthProvider } from "@/providers/auth";
import { Toaster } from "react-hot-toast";
import Footer from "../components/common/Footer";
import localFont from 'next/font/local'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const myFont = localFont({
  src: [
    {
      path: '/fonts/gilroy-regular.ttf',
      weight: '400',
      style: 'normal'
    },
  ]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <div className="flex flex-col min-h-screen bg-gradient-to-b from-whtie to-gray-100 dark:from-neutral-400 dark:to-neutral-500 inter.className">
          <NextAuthProvider>
            <Toaster position="top-center" reverseOrder={false} />
            <Header />
            <main className="flex-grow">
              {children}
            </main>
            <Footer />
          </NextAuthProvider>
        </div>
      </body>
    </html>
  );
}
